INSERT INTO project (name, description, created_at, updated_at) VALUES
('教程研发', '开发技术教程和内容', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('个人待办', '个人任务管理清单', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('学习计划', '技能提升和知识学习规划', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO task (project_id, title, description, status, priority, due_at, created_at, updated_at) VALUES
(1, '编写 Spring Boot 入门教程', '介绍 Spring Boot 基础概念和项目搭建', 'TODO', 1, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 DAY), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1, 'React 前端架构设计', '设计 Vite + React 19 的项目结构', 'IN_PROGRESS', 2, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL 3 DAY), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1, '编写 Gradle 构建指南', 'Gradle 9.x 与 Kotlin DSL 配置说明', 'TODO', 1, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL 10 DAY), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1, 'API 契约文档维护', '维护 OpenAPI 契约与 DTO 同步', 'DONE', 2, DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 2 DAY), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1, '部署流程文档', '编写 CI/CD 部署说明', 'CLOSED', 0, DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(2, '购买日常用品', '牛奶、面包、水果', 'DONE', 0, DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(2, '预约牙科检查', '年度体检', 'TODO', 1, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL 14 DAY), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(2, '整理书房', '清理旧书、归档文件', 'IN_PROGRESS', 0, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL 5 DAY), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(3, '学习 Kubernetes 基础', '完成 K8s 入门课程', 'IN_PROGRESS', 2, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL 21 DAY), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(3, '阅读领域驱动设计', 'DDD 蓝皮书精读', 'TODO', 1, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL 30 DAY), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(3, '完成 TypeScript 高级类型练习', '泛型、条件类型、映射类型', 'DONE', 2, DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 DAY), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO tag (name, created_at, updated_at) VALUES
('紧急', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('重要', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('Bug', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('功能', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('文档', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO task_tags (task_id, tag_id) VALUES
(1, 4), (1, 5),
(2, 2), (2, 4),
(3, 5),
(4, 5), (4, 2),
(9, 2);

INSERT INTO timelog (task_id, hours, work_date, note, created_at) VALUES
(1, '60', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY), '编写入门教程大纲', CURRENT_TIMESTAMP()),
(1, '45', DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY), '收集参考资料', CURRENT_TIMESTAMP()),
(2, '90', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY), '设计组件结构', CURRENT_TIMESTAMP()),
(2, '120', DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY), '搭建项目骨架', CURRENT_TIMESTAMP()),
(2, '60', DATE_SUB(CURRENT_DATE(), INTERVAL 4 DAY), '技术选型调研', CURRENT_TIMESTAMP()),
(4, '30', DATE_SUB(CURRENT_DATE(), INTERVAL 5 DAY), '整理端点清单', CURRENT_TIMESTAMP()),
(4, '45', DATE_SUB(CURRENT_DATE(), INTERVAL 6 DAY), '补充 DTO 定义', CURRENT_TIMESTAMP()),
(5, '60', DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY), '编写部署脚本', CURRENT_TIMESTAMP()),
(6, '20', DATE_SUB(CURRENT_DATE(), INTERVAL 8 DAY), '网购下单', CURRENT_TIMESTAMP()),
(8, '30', DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY), '整理书架', CURRENT_TIMESTAMP()),
(9, '90', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY), 'K8s Pod 概念学习', CURRENT_TIMESTAMP()),
(9, '60', DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY), '安装 Minikube', CURRENT_TIMESTAMP()),
(11, '45', DATE_SUB(CURRENT_DATE(), INTERVAL 4 DAY), '完成泛型练习', CURRENT_TIMESTAMP()),
(11, '30', DATE_SUB(CURRENT_DATE(), INTERVAL 6 DAY), '条件类型笔记', CURRENT_TIMESTAMP());
